name: ShaboozeyRealms
version: 1.0
authors: [PattersNET, nanaNadine]
main: com.shaboozey.realms.ShaboozeyRealms

commands:
    sr:
        description: Lists all commands
        usage: /sr ?
    shart:
        description: Shart on people
        usage: /shart <name>
    srcreate:
        description: Creates a world
        usage: /srcreate <name> <environment>
    srload:
        description: Loads a world
        usage: /srload <name>
    srunload:
        description: Unloads a world
        usage: /srunload <name>
    srdelete:
        description: Deletes a world
        usage: /srdelete <name>
    srtp:
        description: Deletes a world
        usage: /srtp <dest> (name)
    srsetspawn:
        description: Deletes a world
        usage: /srsetspawn
    srimport:
        description: Imports a world
        usage: /srimport <name> <environment>
    srlist:
        description: List all worlds
        usage: /srlist
    srinfo:
        description: Provides information about the world
        usage: /srinfo
    srmobs:
        description: Sets whether a mob can spawn or not
        usage: /srmobs <world> <mob> <value>
    srwho:
        description: Provides the world of a player
        usage: /srwho <player>